#!/bin/bash

if [ $# -lt 1 ];then
	echo "must set qmake absolut path"
	exit
fi
QMAKE=$1
echo "QMAKE=$QMAKE"

cd deps
mkdir lib
cd handy
./build_config
make -j4
cp libhandy.a ../lib
cd ..

cd leveldb-1.20
make -j4
cp -arv out-static/* ../lib
cd ..

cd openssl10
./config
make -j4
cp libssl.a ../lib/libssl10.a
cp libcrypto.a ../lib/libcrypto10.a
cd ..

cd openssl11
./config
make -j4
cp libssl.a ../lib/libssl11.a
cp libcrypto.a ../lib/libcrypto11.a
cd ..

cd ..
cd output
$QMAKE ..

export LIBRARY_PATH=../deps/lib
export LD_LIBRARY_PATH=../deps/lib

make
cp ../tools/p2p.cfg .
cp ../lua/json.lua .
cp ../lua/md5.lua .
rm *.o
rm *.cpp
rm *.h

mkdir opensslbuild
cd opensslbuild
$QMAKE ../../deps/luaopenssl
make
cp libopenssl.so.1.0.0 ../openssl.so
