#!/bin/bash

cd deps
#cd handy
#make clean
#rm -rf ssl
#cd ..

cd leveldb-1.20
make clean
cd ..

cd openssl10
make clean
rm Makefile
cd ..

#cd openssl11
#make clean
#rm Makefile
#cd ..

cd lib
rm -rf db
rm -rf helpers
rm -rf port
rm -rf table
rm -rf util
rm *
cd ..

cd ..
cd output

make clean
rm -rf opensslbuild
rm *
