#ifndef WTCCMDDEFINE_H
#define WTCCMDDEFINE_H

#define SV_CMD_ENTER "ENTR"
#define SV_CMD_LOBBY_NET "LBNT"
#define SV_CMD_QUEUE_SOLO "SOLO"
#define SV_CMD_GAME_NET "GMNT"
#define SV_CMD_GAME_START "GMST"
#define SV_CMD_TICK "TICK"
#define SV_CMD_GAMEOVER "GMOV"

#endif // WTCCMDDEFINE_H
